name: labledger
description: "Medical Records Made Simple"
publish_to: 'none'

version: 3.0.0+3

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  csv: ^8.0.0
  cupertino_icons: ^1.0.9
  dio: ^5.10.0
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_lucide: ^1.11.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.3.0
  font_awesome_flutter: ^11.0.0
  http: ^1.6.0
  intl: ^0.20.3
  open_file_plus: ^3.4.1+1
  package_info_plus: ^9.0.1
  path_provider: ^2.1.6
  pdf: ^3.13.0
  printing: ^5.15.0
  shared_preferences: ^2.5.5
  universal_html: ^2.3.0
  url_launcher: ^6.3.2
  version: ^3.0.2
  window_manager: ^0.5.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    icon_size: 48
  linux:
    generate: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic