name: labledger
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  window_manager: ^0.5.0
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  lucide_icons: ^0.257.0
  hugeicons: ^0.0.11
  fl_chart: ^1.0.0
  intl: ^0.20.2
  dio: ^5.9.0
  version: ^3.0.2
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSansDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSansDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSansDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSansDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSansDisplay-BoldItalic.ttf
          weight: 700
          style: italic

dependency_overrides:
  flutter_secure_storage_windows: ^4.0.0
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
