name: labledger
base: core22
version: '1.0.0'
title: LabLedger
summary: LabLedger - Medical Records Made Simple
description: |
  LabLedger is a Flutter app backed by Django REST Framework for managing lab bills, incentives and patient reports.

grade: stable
confinement: strict
license: Apache-2.0
contact: himanshuchaurasiya24@gmail.com
website: https://github.com/himanshuchaurasiya24/LabLedger
source-code: https://github.com/himanshuchaurasiya24/LabLedger
issues: https://github.com/himanshuchaurasiya24/LabLedger/issues
donation: https://github.com/sponsors/himanshuchaurasiya24

apps:
  labledger:
    command: bin/labledger
    plugs:
      - network
      - home
      - desktop
      - wayland
      - x11
      - network-bind
      - opengl

parts:
  labledger:
    plugin: nil
    source: .
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - liblzma5
      - libstdc++6
      - libsqlite3-0
      - libsecret-1-0
      - libnotify4
    override-build: |
      set -eux
      echo "📦 Copying pre-built Flutter Linux release..."
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/x64/release/bundle/* $CRAFT_PART_INSTALL/bin/
      echo "🖼️ Copying icon and desktop entry..."
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp linux/labledger.desktop $CRAFT_PART_INSTALL/meta/gui/
      cp linux/assets/icons/labledger.png $CRAFT_PART_INSTALL/meta/gui/labledger.png
