name: labledger
base: core22
adopt-info: labledger
title: LabLedger
summary: Medical Records Made Simple
description: |
  LabLedger is a comprehensive medical records and laboratory management
  application designed to simplify the workflow of diagnostic centers and
  medical laboratories. It provides an intuitive interface for managing
  bills, doctors, diagnosis types, franchise labs, and patient records.

license: Apache-2.0
contact: himanshuchaurasiya24@gmail.com
grade: stable
confinement: strict

icon: assets/images/app_icon.png

architectures:
  - build-on: amd64

apps:
  labledger:
    command: bin/labledger
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - network
      - network-bind
      - home
      - unity7
      - gsettings
      - audio-playback

parts:
  flutter-git:
    plugin: nil
    source: https://github.com/flutter/flutter.git
    source-tag: 3.38.3
    source-depth: 1
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libglu1-mesa
      - ninja-build
      - unzip
      - xz-utils
    override-prime: ''

  labledger:
    after: [flutter-git]
    plugin: nil
    source: .
    override-build: |
      set -eux
      
      # Extract version from pubspec.yaml and set it for the snap
      VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: *//' | cut -d'+' -f1)
      snapcraftctl set-version "$VERSION"
      
      # Export Flutter to PATH
      export PATH="$CRAFT_STAGE/../flutter-git/install/usr/bin:$PATH"
      
      # Clean and get dependencies
      flutter clean
      flutter pub get
      
      # Build the Linux application
      flutter build linux --release
      
      # Copy the built application to the install directory
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/x64/release/bundle/* $CRAFT_PART_INSTALL/bin/
      
      # Rename the executable and make it executable
      mv $CRAFT_PART_INSTALL/bin/labledger $CRAFT_PART_INSTALL/bin/.labledger-bin
      
      # Create a wrapper script
      cat > $CRAFT_PART_INSTALL/bin/labledger <<'EOF'
      #!/bin/bash
      set -e
      exec "$SNAP/bin/.labledger-bin" "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/labledger
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libgtk-3-dev
      - ninja-build
      - pkg-config
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
    stage-packages:
      - libgtk-3-0
      - libglu1-mesa
      - libgl1

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
